#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

use Symfony\Component\Console\Application;
use \Webtrees\Geodata\ExportCommand;

$command = new ExportCommand;

$application = new Application('export', '1.0.0');
$application->add($command);
$application->setDefaultCommand($command->getName(), true);
$application->run();
