#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

use \Webtrees\Geodata\ImportCommand;
use Symfony\Component\Console\Application;

$command = new ImportCommand;

$application = new Application('import', '1.0.0');
$application->add($command);
$application->setDefaultCommand($command->getName(), true);
$application->run();
