#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

use \Webtrees\Geodata\WikiFlagCommand;
use Symfony\Component\Console\Application;

$command = new WikiFlagCommand;

$application = new Application('wiki-flag', '1.0.0');
$application->add($command);
$application->setDefaultCommand($command->getName(), true);
$application->run();
